### ISSUE TITLE
CPU fallback version for debugging?

### ISSUE THREAD

**Issue by drewm1980** [kysucix/gipuma#13]
Is there an up-to-date cpu host version that can be used as a reference for debugging?

**Comment by kysucix** [comment]
I'm sorry there is no reference cpu program.

**Comment by drewm1980** [comment]
Do you think your gpu implementation is faster than a (more) straightforward cpu implementation would have been? 

I did a cuda implementation of a face recognition algorithm as part of my doctorate in 2011-2012, and in the end the gpu version was still only marginally faster than the cpu version, even after multiple re-writes of the gpu version and practically exhausting all of the options for data layout, etc... The working set at which our algorithm was data parallel could easily fit into cpu L3 cache, but had to be streamed from RAM on the gpu.

**Comment by kysucix** [comment]
Hi, it's highly unlikely that a cpu version would be even in a similar order of magnitude for such a highly parallel algorithm.

**Comment by drewm1980** [comment]
Unfortunately, data parallelism alone is not sufficient for an algorithm to
map well to the GPU; that is just a rule of thumb for whether you should
even bother trying to port your CPU code.

If your code is doing something local (so it fits in CPU cache) and
iterative ( so you hit the cache most of the time) like optimizing the
angle of a patch (or in my case it was tiny pictures of faces for face
recognition) , the CPU's memory architecture can be faster than the GPU's.

Most people do it in the other direction, but if you have performance
bottlenecks, or are unsure about correctness of some parts, porting only
those to the CPU is an option that is still open to you.

**Comment by kysucix** [comment]
Hi,

I was not completely correct when saying that I don't have a reference CPU code. Actually we started from a CPU running multiple threads per each row, thus making heavy use of cpu cache. Nevertheless the program at the end was several order of magnitude slower than the current one.

I still believe this is a very fast implementation when comparing to the competitors (look at middlebury benchmark) also because the algorithm is specifically tailored for the GPU and its implementation make use of very specific GPU features (textures for images and shared memory for reference camera)
