### ISSUE TITLE
Gipuma reloads and decodes source image files repeatedly

### ISSUE THREAD

**Issue by drewm1980** [kysucix/gipuma#21]
Is there some non-historical reason why gipuma is called repeatedly from a shell script (and thus has to load everything from scratch)? Gipuma is loading and decoding the same N source images N times!

On our TITAN X with an i7 rig with SSD, the full dinoSparseRing takes 37s, much less than the 2 min 52 sec submitted to the middlebury stereo.  TITAN X is only about 30% faster than a GTX 980, not 6X as fast... so the submitted number seems way off.

Is the result listed as "ECCV2016_104" just the current version of gipuma? That is closer in speed to what I'm seeing.

**Comment by kysucix** [comment]
Hi,

The idea of running everytime the program from scratch is to parallelize the computation on multiple GPUs. In this way you have an runtime speedup linear with the number of GPU available. Of course it make more sense in case you have bigger dataset and images, with dinoSparseRing it's pointless.

We were fair when submitting the runtime to the muddlebury benchmark and considered the overall script duration including disk i/o and the (multiple) loading of input images (consider I do not have an SSD). Additionally you must include the runtime of the Poisson Surface reconstruction.
Ah and finally, even if we declare that all the computation was done on GPU, the script on Middlebury "normalized" our runtime with respect to a cpu with 3.0GHZ, and since I have a 3.2GHZ machine the timing were penalized. Add a 30% decrease in the equation due to my GTX 980 and you approach easily 2 min 52 sec.

No ECCV2016_104 is not me, maybe it's someone else using or improving gipuma :)

**Comment by drewm1980** [comment]
Ah, that makes sense. Thanks for the explanation! I bet there's a way to do multi-gpu directly with the CUDA api these days.
